version: "3"

services:
  doof_client:
    container_name: doof_client
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_RESTAURANT_NAME=${VITE_RESTAURANT_NAME}
